"""Smoke-test the actual image → MediaPipe → alphabet path on source LSP images.

This is an integration check, not an independent accuracy test. Some images may
have contributed references. Validation split metrics are generated by the builder.
"""

import argparse
import json
from pathlib import Path
from time import perf_counter

import cv2
import numpy as np

from alphabet_model import AlphabetModel, MODEL_DIR
from gestures import HandAnalyzer


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument("lsp_images", type=Path)
    args = parser.parse_args()
    model = AlphabetModel("LSP")
    outcomes = []
    for letter in ("A", "N", "T"):
        for number in (1, 30, 60, 90, 120):
            path = args.lsp_images / letter.lower() / f"{letter.lower()} ({number}).jpg"
            image = cv2.imread(str(path))
            analyzer = HandAnalyzer("Landmarks", num_hands=1)
            try:
                start = perf_counter()
                result = analyzer.analyze({"Color": cv2.cvtColor(image, cv2.COLOR_BGR2BGRA),
                                           "color_timestamp": 8000, "color_sequence": 1})
                prediction = model.recognize(result["hands"][0]) if result["hands"] else {"letter": None}
                outcomes.append({"image": str(path.relative_to(args.lsp_images)),
                                 "expected": letter, "prediction": prediction,
                                 "milliseconds": (perf_counter() - start) * 1000})
            finally:
                analyzer.close()
    timing = {}
    for language in ("LSP", "ASL"):
        classifier = AlphabetModel(language)
        durations = []
        for sample in classifier.samples[:100]:
            start = perf_counter()
            classifier.predict(sample)
            durations.append((perf_counter() - start) * 1000)
        timing[language] = {"median_ms": float(np.median(durations)),
                            "p95_ms": float(np.percentile(durations, 95))}
    report = {"purpose": "integration smoke test on source images, not independent accuracy",
              "outcomes": outcomes, "classification_timing": timing}
    (MODEL_DIR / "runtime-smoke.json").write_text(json.dumps(report, indent=2))
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
